### ISSUE TITLE
Grafik auf neuesten Stand bringen

### ISSUE THREAD

**Issue by RM-Redakteur** [DE-MG-RM-PM-TR/DE-MG-RM-PM-TR-VM-Device-Doc#3]
Entspricht nicht mehr dem Aussehen aktueller Geräte
die zwei Weichen (AB, A/B) müssen voneinander abgegrenzt werden.
(A1/B1m A2/B2). Dazu muss auch der Absatz unter dem Bild angepasst werden. 

DE-MG-RM-PM-TR-VM-Device-Doc/TEST-Oxygen-Manual/de-de/Montage_-7338.dita

**Comment by monafels** [comment]
Ist erledigt, aber wie besprochen (AB, A/B) mit (AB;a/b) ausgetauscht
